version: '3.3'

services:
  jrtb-db:
    image: mysql:8.0.15
    restart: always
    container_name: dev-jrtb-db
    environment:
      MYSQL_DATABASE: 'dev_jrtb_db'
      # So you don't have to use root, but you can if you like
      MYSQL_USER: 'dev_jrtb_db_user'
      # You can use whatever password you like
      MYSQL_PASSWORD: 'dev_jrtb_db_password'
      # Password for root access
      MYSQL_ROOT_PASSWORD: 'root'
    ports:
      # <Port exposed> : < MySQL Port running inside container>
      - '3307:3306'
    expose:
      # Opens port 3307 on the container
      - '3307'
    command: --character-set-server=utf8 --collation-server=utf8_general_ci